import pandas as pd
import matplotlib.pyplot as plt

def generate_global_plots():
    print("="*75)
    print("[RUNNING] REALQM STUDIO: COMPILING GLOBAL SEGRÈ MANIFOLD PLOTS...")
    print("="*75)
    
    csv_file = "global_relaxed_valley_telemetry.csv"
    try:
        # Read the compiled database generated by SunDance
        df = pd.read_csv(csv_file)
    except Exception as e:
        print(f"[ERROR] Could not read csv file: {e}")
        print("Please verify the simulation run has completely finished.")
        return

    # Filter out baseline anomalies (like Hydrogen defaults) to keep the curve clean
    df_filtered = df[df['Graph_Radius'] > 0]

    # 1. Create a 2-Panel Master Plot for the 200th Publication
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), sharex=True)
    
    # Upper Panel: Global Graph Laplacian Radius Curve
    ax1.plot(df_filtered['Z'], df_filtered['Graph_Radius'], color='#1F4E79', linestyle='none', marker='.', alpha=0.6, label='Isotope Manifest')
    ax1.set_title("Unified Segrè Chart Matrix Manifold (Z=1 to 118)", fontweight='bold', fontsize=14, color='#1F4E79')
    ax1.set_ylabel("Spectral Graph Radius (Size Operator)", fontsize=11)
    ax1.grid(True, linestyle=':', alpha=0.6)
    ax1.legend(loc='upper left')

    # Lower Panel: Relaxed Fiedler Stiffness Stability Valley
    ax2.plot(df_filtered['Z'], df_filtered['Relaxed_Fiedler_Stiffness'], color='darkred', linestyle='none', marker='o', alpha=0.7, label='Relaxed Network Rigidity')
    
    # Highlight the Symmetrical Super-Anchors explicitly (Fixed with .iloc[0])
    iron_peak = df_filtered[df_filtered['Z'] == 26]
    if not iron_peak.empty:
        ax2.scatter(iron_peak['Z'].iloc[0], iron_peak['Relaxed_Fiedler_Stiffness'].max(), color='gold', s=150, edgecolors='black', zorder=5, label='Iron-56 Cosmic Climax')

    ax2.set_xlabel("Atomic Number (Proton Count Z)", fontsize=11)
    ax2.set_ylabel("Relaxed Fiedler Stiffness ($\lambda_1$)", fontsize=11)
    ax2.grid(True, linestyle=':', alpha=0.6)
    ax2.legend(loc='upper right')

    plt.tight_layout()
    output_png = "global_relaxed_stability_manifold.png"
    plt.savefig(output_png, dpi=200, bbox_inches='tight')
    plt.close()
    
    print(f"[SUCCESS] Global stability landscape graphic saved successfully as '{output_png}'!")
    print("="*75)

if __name__ == "__main__":
    generate_global_plots()
